openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1

tags:
  - name: auth
  - name: user
  - name: product
  - name: review
  - name: order

paths:
  /auth/logout:
    get:
      tags:
        - auth
      summary: Logout User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: john.doe@gmail.com
                password: thesecret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/register:
    post:
      tags:
        - auth
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: John Doe
                email: john.doe@gmail.com
                password: thesecret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users:
    get:
      tags:
        - user
      summary: Get All Users
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/62a1ca76d62777460df75041:
    get:
      tags:
        - user
      summary: Get Single User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/showCurrentUser:
    get:
      tags:
        - user
      summary: Get Current User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/updateUserProfile:
    patch:
      tags:
        - user
      summary: Update User Profile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Jane Doe
                email: jane.doe@gmail.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/updateUserPassword:
    patch:
      tags:
        - user
      summary: Update User Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                oldPassword: thesecret
                newPassword: onlysecret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products:
    get:
      tags:
        - product
      summary: Get All Products
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - product
      summary: Create Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: emperor bed
                price: 23999
                description: >-
                  Cloud bread VHS hell of banjo bicycle rights jianbing umami
                  mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr
                  dreamcatcher waistcoat, authentic chillwave trust fund. Viral
                  typewriter fingerstache pinterest pork belly narwhal. Schlitz
                  venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki
                  trust fund hashtag kinfolk microdosing gochujang live-edge
                image: >-
                  https://dl.airtable.com/.attachmentThumbnails/0446e84c5bca9643de3452a61b2d6195/1b32f48b
                category: bedroom
                company: ikea
                colors:
                  - "#0000ff"
                  - "#000"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products/62a37f66ea6bfcf12484abeb:
    get:
      tags:
        - product
      summary: Get Single Product
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - product
      summary: Update Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: accent chair
                price: 15999
                description: >-
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                  irure dolor in reprehenderit in voluptate velit esse cillum
                  dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                  cupidatat non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products/629d52b2a968c1acfd22fea3/reviews:
    get:
      tags:
        - product
      summary: Get Single Product Reviews
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products/uploadImage:
    post:
      tags:
        - product
      summary: Upload Image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /products/62a30bdb121dae2cd284c8ef:
    delete:
      tags:
        - product
      summary: Delete Product
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /reviews:
    get:
      tags:
        - review
      summary: Get All Reviews
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - review
      summary: Create Review
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Super comfy. Great for backpain!
                rating: 4
                comment: >-
                  It ease up and relieve my backpain a lot. Definitely worth the
                  price.
                product: 62a37f66ea6bfcf12484abeb
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /reviews/62a38226f81c263eaccb04df:
    get:
      tags:
        - review
      summary: Get Single Review
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - review
      summary: Update Review
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Its good but ain't durable
                rating: 3
                comment: >-
                  I buy it around 1 month ago. At first it helps me a lot with
                  my backpain but lately it make some 'cricket sound' that may
                  indicate some part is already broken.
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /reviews/629d55d0a968c1acfd22fedb:
    delete:
      tags:
        - review
      summary: Delete Review
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - order
      summary: Get All Orders
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - order
      summary: Create Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tax: 499
                shippingFee: 799
                items:
                  - name: accent chair
                    price: 15999
                    image: >-
                      https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
                    amount: 3
                    product: 62a37f66ea6bfcf12484abeb
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /orders/62a384a7f81c263eaccb04f1:
    get:
      tags:
        - order
      summary: Get Single Order
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /orders/showAllMyOrders:
    get:
      tags:
        - order
      summary: Get Current User Orders
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /orders/629d5675a968c1acfd22fef5:
    patch:
      tags:
        - order
      summary: Update Status Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                paymentIntentID: paidUsingFakeStripePaymentIntentID
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
